---
- name: Installation using package manager for Ubuntu or Debian distribution
  ansible.builtin.import_tasks: ubuntu_debian.yml
  when: (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian") and not manual_installation
- name: Installation using package manager for RedHat or CentOS distribution
  ansible.builtin.import_tasks: rhel_centos.yml
  when: (ansible_distribution == "RedHat" or ansible_distribution == "CentOS") and not manual_installation
- name: Manual installation
  ansible.builtin.import_tasks: manual_installation.yml
  when: manual_installation
