---
- name: Install dependencies packages
  ansible.builtin.apt:
    name:
      - gpg
      - unzip
    state: present
    update_cache: yes

# - name: Get Hashicorp key
#   block:
#     - name: Download the key
#       command: >
#         wget -O- https://apt.releases.hashicorp.com/gpg |
#          gpg --dearmor |
#          sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

#     - name: Verify the finger print
#       command: >
#         gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint

#     - name: Add repo
#       command: >
#         echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

- name: Get Hashicorp key
  block:
    - name: Get Hashicorp apt key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /etc/apt/trusted.gpg.d/hashicorp-archive-keyring.asc
        mode: "644"
        force: true
    # - name: Add Hashicorp apt key
    #   ansible.builtin.apt_key:
    #     url: https://apt.releases.hashicorp.com/gpg
    #     state: present

    - name: Add Hashicorp repo to apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
  rescue:
    - name: Print when errors
      ansible.builtin.debug:
        msg: "Problem during add key and Hashicorp repo to apy source"

- name: Install terraform
  ansible.builtin.apt:
    name: terraform
    state: present
    update_cache: yes
