---
# vars file for roles/install-terraform
manual_installation: "{{ lookup('ansible.builtin.env', 'MANUAL_INSTALLATION', default='false') }}"
terraform_install_directory: "/usr/local/bin"
system_version: "linux_amd64"
terraform_version: "1.1.3"
terraform_download_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_{{ system_version }}.zip"
