---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  vars:
    manual_installation: "{{ lookup('ansible.builtin.env', 'MANUAL_INSTALLATION') }}"
    terraform_install_directory: "/usr/local/bin"
  tasks:
    - name: "Debug: print MANUAL_INSTALLATION variable"
      ansible.builtin.debug:
        var: manual_installation

    - name: "Verification in case package manager was used for the installation"
      when: manual_installation == "false"
      block:
        - name: Gather the package facts
          ansible.builtin.package_facts:
            manager: auto

        - name: Check whether Terraform is installed using package manager
          ansible.builtin.assert:
            that: true
          when: "'terraform' in ansible_facts.packages"
      rescue:
        - name: "Print while errors"
          ansible.builtin.debug:
            msg: "Error during verification"

    - name: "Verification in case of manual installation"
      when: manual_installation == "true"
      block:
        - name: Gather the package facts
          ansible.builtin.stat:
            path: "{{ terraform_install_directory }}/terraform"
          register: terraform

        - name: Check whether Terraform is installed manually
          ansible.builtin.assert:
            that: "terraform.stat.exists"
      rescue:
        - name: "Print while errors"
          ansible.builtin.debug:
            msg: "Error during verification"
