name: Ansibel CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Install docker on the ubuntu runner
      - uses: docker-practice/actions-setup-docker@master

      # Check docker installation
      - name: Run docker version command
        run: docker version

      # Print the current directory
      - name: Print the current directory
        run: pwd

      # Install dependencies
      - name: Create virtual env
        run: |
          python3 -m virtual_env molecule_env
          source molecule_env/bin/activate
          pip3 install ansible molecule molecule-docker yamllint ansible-lint

      # Change the working directory
      - name: Change the working directory
        run: cd terraform/ansible/roles/install_terraform/

      # Run molecule lint
      - name: Linting
        run: molecule lint

      - name: Playbook
        run: molecule converge

      - name: verification"
        run: molecule verify

      - name: Checking idempotency
        run: molecule idempotence
